[CMOB-1459] Design
bchmsl/QuizApp pull request #1
Opened 2023-05-16 13:04 UTC by bchmsl

https://spaceneobank.atlassian.net/browse/CMOB-1459

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/base/fragment/BaseFragment.kt
> +    abstract fun inflate(): Inflater<VB>
ბაინდინგის ექსთენშენი გამოიყენე

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/fragment_home.xml
> +        style="@style/Base.Widget.AppCompat.TextView.BaseTextView.NormalText"
სტილის სახელი როგორც წინა პროექტში ეგრე გერწეროს და სტილში გაუწერე მშობელი თუ გჭირდება ან რამე

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/drawable/shape_oval.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval"/>
ცარიელი გაქ შეგიძლია წაშალო

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/drawable/shape_rect_rounded.xml
> +    <corners android:radius="16dp"/>
ჰარდად გიწერია

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/fragment_points_earned.xml
> +        tools:visibility="visible" />
დეფოლტად ისეც ხილვადია არ უნდა ეს ატრიბუტი

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/layout_dialog_prompt.xml
> +            android:id="@+id/btnYes"
ისევ btn, დააწერე სრულად

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/layout_dialog_prompt.xml
> +            android:id="@+id/btnNo"
აქაც

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/layout_score_section.xml
> +        android:paddingVertical="@dimen/dimen_20_dp"
პირდაპირ პადინგ გამოიყენე

2023-05-17 12:34 UTC, Gio481 commented on app/src/main/res/layout/layout_score_section.xml
> +            android:backgroundTint="#FFFFFF"
ფერი ქოლორებში

2023-05-18 07:16 UTC, bchmsl commented on app/src/main/res/drawable/shape_oval.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval"/>
არაა ცარიელი, item_subject-ში ვიყენებ

2023-05-18 07:23 UTC, bchmsl commented on app/src/main/res/layout/fragment_points_earned.xml
> +        tools:visibility="visible" />
ვტესტავდი ამ სქრინს და მაგიტო დავტოვე ეს პარამეტრი

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/layout/layout_score_section.xml
> +            android:backgroundTint="#FFFFFF"
Done ✅

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/layout/layout_score_section.xml
> +        android:paddingVertical="@dimen/dimen_20_dp"
Done ✅

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/layout/layout_dialog_prompt.xml
> +            android:id="@+id/btnNo"
Done ✅

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/layout/layout_dialog_prompt.xml
> +            android:id="@+id/btnYes"
Done ✅

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/drawable/shape_rect_rounded.xml
> +    <corners android:radius="16dp"/>
Done ✅

2023-05-18 07:37 UTC, bchmsl commented on app/src/main/res/layout/fragment_home.xml
> +        style="@style/Base.Widget.AppCompat.TextView.BaseTextView.NormalText"
Done ✅

2023-05-23 17:28 UTC, Gio481 approved these changes

2023-05-29 08:30 UTC, AnaRusadze requested changes

2023-05-29 08:30 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/ui/question/view/CustomGreyVector.kt
> +            addCircle(centerX2, centerY, radius, Path.Direction.CW)
დაფიქსე ის ბაგი, როცა პატარა დივაისზე ორივე წრე შიგნით იწევა და ფორმები ეცვლება

2023-05-29 08:30 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_points_earned.xml
> +        tools:visibility="visible" />
თუ android:visibility = "gone" an "invisible" არ წერია, ე.ი გამოჩნდება იქსემელში და თულსის დამატება არ დაგჭირდება

2023-06-13 12:26 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-21 08:41 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +}
ბაჩი ენამში ვალიდეითის ლოგიკის შეცვლა სხვა ბრენჩზე გაქვს?

2023-06-21 08:41 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/ui/home/fragment/QuizHomeFragment.kt
> +                greetingTextView.text = getString(S.greeting).plus("${user.userName}!")
ფლასის მაგივრად სტრინგი დააფორმატირე

2023-06-21 08:41 UTC, AnaRusadze commented on app/src/main/java/com/space/quizapp/presentation/ui/question/view/QuizAnswerOptionView.kt
> +            starsTextView.text = "+1"
ქულის რიცხვი არ უნდა იყოს სტატიკური სტრინგი, კარგი იქნება რომ პასუხების მოდელ კლასში ქულის ცვლადი დაამატო, რომელიც დეფოლტად ერთიანი იქნება და ამ კლასშიც ადაპტერიდან წამოიღე. ეგრე საშუალება გვექნება, რომ სფეისში მოთხოვნის შემთხვევაში სხვადასხვა პასუხი სხვადასხვა ქულიანი გავხადოთ

2023-06-21 08:43 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/question/view/QuizAnswerOptionView.kt
> +            starsTextView.text = "+1"
ქულის ცვლადი ბოლო ბრენჩზე მაქვს შექმნილი (refactor)

2023-06-21 08:44 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +}
არ შემიცვლია ლოგიკა, ჯერჯერობით იგივე დავტოვე

2023-06-21 09:39 UTC, merged