[CMOB-1704] Quiz Functionality
bchmsl/QuizApp pull request #5
Opened 2023-06-12 08:54 UTC by bchmsl

https://spaceneobank.atlassian.net/browse/CMOB-1704

Quiz Functionality Implementation

On this branch:
- Added API request to retrieve subjects on Home Fragment,
- API response (Subjects and Questions) caches in Room Database to follow Single Source of Truth,
- After tapping on Subject, corresponding Questions are retrieved from local database,
- Upon answering, it compares the answer to the correct answer and adds points to user or not

To-do list:
On the next branch I will:
- Add user points to database to corresponding subject
- Modularize app to separate Quiz functionality,
- Convert an app to MVI architecture pattern

Known bugs:
- When I press "შემდეგი" button on Question Fragment followed by answer option instantly, an application crashes,
- Start button on Home Fragment does not work (needs onClickListener)
- Short names are not allowed (needs to change minimum length)

2023-06-12 12:56 UTC, Gio481 requested changes

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/common/util/ApiHelper.kt
> +            QuizResource.Error(QuizCustomThrowable(e.message))
do you really need to check if body is null or not ?
also there is error body, it will be good if you parse it and use it

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/common/util/QuizCustomThrowable.kt
> +
you can use private set

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/di/QuizRepositoryModule.kt
> +        )
add mappers in di module and use get() here

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/di/QuizRetrofitModule.kt
> +    retrofit.create(QuizQuestionsApiService::class.java)
single { get<Retrofit>().create(QuizQuestionsApiService::class.java) }

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/dao/QuizUserDao.kt
> +    suspend fun checkUser(username: String): String?
getUserOrNull will be preferable name I think

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/dao/QuizUserSubjectsDao.kt
> +    suspend fun retrieveUserSubjects(username: String): QuizUserSubjectEntity
seems this function needs to return list of QuizUserSubjectEntity

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/ListStringConverter.kt
> +}
what is this for

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/QuizQuestionEntity.kt
> +}
useless {}

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionDomainEntityMapper.kt
> +    override fun invoke(model: QuizQuestionDomainModel): QuizQuestionEntity {
add line :d

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionDomainEntityMapper.kt
> +        )
with(model)

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionEntityDomainMapper.kt
> +    override fun invoke(model: QuizQuestionEntity): QuizQuestionDomainModel {
add empty line

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionEntityDomainMapper.kt
> +            questionIndex = model.questionIndex
you really like this mapper class ? ;d need some optimisation

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/subject/QuizSubjectDomainEntityMapper.kt
> +        )
empty line and with()

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/subject/QuizSubjectEntityDomainMapper.kt
> +        )
with(model)

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/remote/model/mapper/question/QuizQuestionDtoDomainMapper.kt
> +    }
it is not clear mapper class

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/repository/BaseRepository.kt
> +abstract class BaseRepository
what is this

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/repository/quiz/QuizRepositoryImpl.kt
> +
like a train, needs some optimisation

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/data/repository/user/QuizUserDataRepositoryImpl.kt
> +    override suspend fun getUserTokenIfExists(username: String): String? {
getUserTokenOrNull

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/model/quiz/QuizQuestionDomainModel.kt
> +    )
same here

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/repository/quiz/QuizRepository.kt
> +}
you dont need BaseRepository, and why is QuizRepository abstract ?

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +//    protected val quizManager by inject<QuizManager>(QuizManager::class.java)
remove it if you dont need

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +abstract class CheckAnswersUseCase :
use case abstract class ? why

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/next_question/GetNextQuestionUseCase.kt
> +//    protected val questionManager by inject<QuizManager>(QuizManager::class.java)
remove it

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +    protected val quizManager = KoinJavaComponent.get<QuizManager>(QuizManager::class.java)
pass they in constructor

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/quiz/retrieve_questions/QuizRetrieveQuestionsUseCase.kt
> +}
use constructor

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/quiz/retrieve_subjects/QuizRetrieveSubjectsUseCase.kt
> +    protected val repository by inject<QuizRepository>(QuizRepository::class.java)
use constructor

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/user/read_user_data/QuizRetieveUserDataUseCaseImpl.kt
> +        }
use when and use the readUserTokenUC() directly
what is UC in function name

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/user/read_user_data/QuizRetrieveUserDataUseCase.kt
> +}
what you need is make use cases regular classes and use repository for other repositories or classes

2023-06-12 12:56 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/base/fragment/QuizBaseFragment.kt
> +    val binding get() = _binding!!
just use viewBinding extension

2023-06-13 06:30 UTC, Gio481 requested changes

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/adapter/QuizSubjectsAdapter.kt
> +                    itemCallback?.invoke(model)
why dont you have clickListener in the onCreateViewHolder

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +        vm.retrieveSubjects()
what is this for

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +            }.show()
if you write something like that
showDialog(block: QuizDialogPromptView.() -> Unit){
  QuizDialogPromptView(requireContext).apply(block)
}
try this function :d and you dont need onNegativeButtonListener you are doing nothing, also you dont need dialog.dismiss() in onPositiveButtonListener

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/view/QuizScoreView.kt
> +        }
only one component so you dont need with(binding)

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/vm/QuizHomeViewModel.kt
> +
empty line :d

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/vm/QuizHomeViewModel.kt
> +    private val userDomainUiMapper: QuizUserDomainUiMapper,
dont need UC in names

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/vm/QuizHomeViewModel.kt
> +    val loadingState get() = _loadingState.asStateFlow()
add some other classes or extensions to avoid two variables every time

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/fragment/QuizPointsFragment.kt
> +        binding.notEarnedTextView.visibility = View.VISIBLE
with(binding)
in the other fragment you have super.onBind but not here, fix code style issue

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/adapter/AnswersAdapter.kt
> +            }
with(binding.root)

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +            AnswerOptionsRecyclerView.adapter = answersAdapter
is AnswerOptionsRecyclerView id ?

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +            }.show()
same here

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/manager/QuizManager.kt
> +
needs format

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/util/QuizAnswerSelectedState.kt
> +    ANSWER_UNSELECTED
just CORRECT, INCORRECT and UNSELECTED

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/vm/QuizQuestionViewModel.kt
> +        executeAsync(IO) {
I think IO should be default

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_home.xml
> +        android:layout_height="96dp"
dimensions

2023-06-13 06:30 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_question.xml
> +    android:orientation="vertical"
orientation is unnecessary or you need this one?

2023-06-13 09:28 UTC, Gio481 commented on app/build.gradle
> +
if you want add BuildSrc module for grade where you have libraries and versions, here you will use just
implementation Libraries.Retrofit and etc.
also if you want make base gradle where you have some bases for every gradle

2023-06-13 12:54 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space/quizapp/domain/usecase/user/save_user_data/QuizSaveUserDataUseCaseImpl.kt
> +            }
unbelievable :)

2023-06-13 13:03 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +        binding.nextButton.setOnClickListener {
use with(binding)

2023-06-18 10:51 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/ListStringConverter.kt
> +}
This type converter is for storing answers, where question answers is List<String> and I am saving it as a single string using TypeConversion

2023-06-18 10:57 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/repository/BaseRepository.kt
> +abstract class BaseRepository
Extra layer of abstraction for all the repositories

2023-06-18 10:59 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/repository/quiz/QuizRepositoryImpl.kt
> +                }
Well... I think it's about preference, because it is quite clear to me. If you have any suggestions, I would appreciate them

2023-06-18 11:01 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/repository/quiz/QuizRepository.kt
> +}
Because I have an implementation for this :D 
That way UseCase does not depend on concrete implementation, but abstraction (SOLID - D)

2023-06-18 11:12 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/base/viewmodel/QuizBaseViewModel.kt
> +            }
it casts to String, Parcelable and Int

2023-06-18 11:14 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/QuizNavigationView.kt
> +    }
I do :D

2023-06-18 11:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/common/util/ApiHelper.kt
> +            QuizResource.Error(QuizCustomThrowable(e.message))
Done ✅

2023-06-18 11:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/common/util/QuizCustomThrowable.kt
> +
Done ✅

2023-06-18 11:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/di/QuizRepositoryModule.kt
> +        )
Done ✅

2023-06-18 11:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/di/QuizRetrofitModule.kt
> +    retrofit.create(QuizQuestionsApiService::class.java)
Done ✅

2023-06-18 11:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/dao/QuizUserDao.kt
> +    suspend fun checkUser(username: String): String?
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/dao/QuizUserSubjectsDao.kt
> +    suspend fun retrieveUserSubjects(username: String): QuizUserSubjectEntity
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/QuizQuestionEntity.kt
> +}
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionDomainEntityMapper.kt
> +    override fun invoke(model: QuizQuestionDomainModel): QuizQuestionEntity {
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionDomainEntityMapper.kt
> +        )
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionEntityDomainMapper.kt
> +    override fun invoke(model: QuizQuestionEntity): QuizQuestionDomainModel {
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/question/QuizQuestionEntityDomainMapper.kt
> +            questionIndex = model.questionIndex
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/subject/QuizSubjectDomainEntityMapper.kt
> +        )
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/quiz/mapper/subject/QuizSubjectEntityDomainMapper.kt
> +        )
Done ✅

2023-06-18 11:32 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/database/model/user/mapper/user/QuizUserEntityDomainMapper.kt
> +        )
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/datastore/QuizDataStoreManager.kt
> +
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/local/datastore/QuizUserDataStoreManager.kt
> +    }
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/remote/model/QuizSubjectDto.kt
> +    )
I prefer nested classes if it is not needed separately

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/remote/model/mapper/question/QuizQuestionDtoDomainMapper.kt
> +    }
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/remote/model/mapper/subject/QuizSubjectDtoDomainMapper.kt
> +        )
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/remote/service/QuizQuestionsApiService.kt
> +    }
Done ✅

2023-06-18 11:33 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/repository/quiz/QuizRepositoryImpl.kt
> +
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/repository/user/QuizUserDataRepositoryImpl.kt
> +    override suspend fun getUserTokenIfExists(username: String): String? {
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +//    protected val quizManager by inject<QuizManager>(QuizManager::class.java)
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +abstract class CheckAnswersUseCase :
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/next_question/GetNextQuestionUseCase.kt
> +//    protected val questionManager by inject<QuizManager>(QuizManager::class.java)
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/check_answers/CheckAnswersUseCase.kt
> +    protected val quizManager = KoinJavaComponent.get<QuizManager>(QuizManager::class.java)
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/quiz/retrieve_questions/QuizRetrieveQuestionsUseCase.kt
> +}
Done ✅

2023-06-18 11:34 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/quiz/retrieve_subjects/QuizRetrieveSubjectsUseCase.kt
> +    protected val repository by inject<QuizRepository>(QuizRepository::class.java)
Done ✅

2023-06-18 11:35 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/user/read_user_data/QuizRetieveUserDataUseCaseImpl.kt
> +        }
When - Done ✅
UC is UseCase

2023-06-18 11:35 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/user/read_user_data/QuizRetrieveUserDataUseCase.kt
> +}
Done ✅

2023-06-18 11:35 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/domain/usecase/user/save_user_data/QuizSaveUserDataUseCaseImpl.kt
> +            }
Done ✅

2023-06-18 11:36 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/base/fragment/QuizBaseFragment.kt
> +            }
Done ✅

2023-06-18 11:36 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/base/viewmodel/QuizBaseViewModel.kt
> +        viewModelScope.launch {
Done ✅

2023-06-18 11:36 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/di/QuizViewModelModule.kt
> +            QuizUserUiDomainMapper()
Done ✅

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/model/quiz/QuizQuestionUiModel.kt
> +}
Exactly which part is unclear? :D

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/model/quiz/mapper/question/QuizQuestionDomainUiMapper.kt
> +    }
Done ✅

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/model/quiz/mapper/question/QuizQuestionUiDomainMapper.kt
> +            questionIndex = model.questionIndex
Done ✅

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/QuizNavigationView.kt
> +        }
Done ✅

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/QuizSubjectView.kt
> +            startButton.setIconResource(D.quiz_ic_next)
Done ✅

2023-06-18 11:37 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/adapter/QuizSubjectsAdapter.kt
> +                    itemCallback?.invoke(model)
Done ✅

2023-06-18 11:38 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +        vm.retrieveSubjects()
To start retrieving info as soon as possible

2023-06-18 11:39 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +            }.show()
I am going to use Builder pattern anyways

2023-06-18 11:39 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/vm/QuizHomeViewModel.kt
> +
Done ✅

2023-06-18 11:39 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/adapter/AnswersAdapter.kt
> +            }
Done ✅

2023-06-18 11:40 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +            AnswerOptionsRecyclerView.adapter = answersAdapter
I think so, I will use first letter lowercase

2023-06-18 11:41 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/manager/QuizManager.kt
> +
Done ✅

2023-06-18 11:41 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/util/QuizAnswerSelectedState.kt
> +    ANSWER_UNSELECTED
I needed the fourth one....

2023-06-18 11:41 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_start/vm/QuizStartViewModel.kt
> +            if (token != QuizUserDataStoreManager.EMPTY_STRING) {
I do... :/

2023-06-18 11:42 UTC, bchmsl commented on app/src/main/res/layout/quiz_fragment_home.xml
> +    android:orientation="vertical"
Done ✅

2023-06-18 11:42 UTC, bchmsl commented on app/src/main/res/layout/quiz_fragment_home.xml
> +        android:layout_height="96dp"
Done ✅

2023-06-18 11:42 UTC, bchmsl commented on app/src/main/res/layout/quiz_fragment_question.xml
> +    android:orientation="vertical"
Done ✅

2023-06-18 11:42 UTC, bchmsl commented on app/src/main/res/layout/quiz_fragment_start.xml
> +    android:orientation="vertical"
Done ✅

2023-06-18 11:42 UTC, bchmsl commented on app/build.gradle
> +
When I start modularization. It's too early yet

2023-06-18 11:42 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizDialogPromptView.kt
> +
Done ✅

2023-06-18 11:43 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizDialogView.kt
> +
Done ✅

2023-06-18 11:43 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +        binding.nextButton.setOnClickListener {
Done ✅

2023-06-19 08:52 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +enum class QuizValidateUser(@StringRes val message: Int) {
სახელი

2023-06-19 08:52 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +        fun validate(s: String): QuizValidateUser {
userName

2023-06-19 08:52 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/data/repository/quiz/QuizRepositoryImpl.kt
> +                    .map { subjectDtoMapper.toDomain(it) }
მაპერის ბეიზში გაიტანე ლისტის გადამაპვა

2023-06-19 08:52 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/data/repository/user/QuizUserSubjectRepositoryImpl.kt
> +        userSubjectsDao.insertUserSubject(userSubjectEntity)
იუზქეისებში გადაანაწილე ლოგიკა

2023-06-19 08:52 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/adapter/QuizSubjectsAdapter.kt
> +            with(binding) {
.root

2023-06-19 10:24 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +enum class QuizValidateUser(@StringRes val message: Int) {
Done ✅

2023-06-19 10:24 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/common/util/QuizValidateUser.kt
> +        fun validate(s: String): QuizValidateUser {
Done ✅

2023-06-19 10:24 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/data/repository/quiz/QuizRepositoryImpl.kt
> +                    .map { subjectDtoMapper.toDomain(it) }
Done ✅

2023-06-19 10:24 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/adapter/QuizSubjectsAdapter.kt
> +            with(binding) {
Done ✅

2023-06-21 11:51 UTC, AleksandreGalogreBaramidze commented
next time try to create smaller pr. pr naming should be more accurate. not like QUIZ FUNCTIONALITY or BUSINESS LOGIC :)  checking this kind of prs is time consuming and most likely review time will be longer than usual. that will cause delay of merging and it will be your blocker to finish the application :). @bchmsl

2023-06-21 11:52 UTC, AleksandreGalogreBaramidze commented
@shioandghuladze @Gio481 please check your comments if they are resolved <3

2023-06-21 11:57 UTC, shioandghuladze commented on app/src/main/java/com/space/quizapp/data/repository/user/QuizUserSubjectRepositoryImpl.kt
> +        userSubjectsDao.insertUserSubject(userSubjectEntity)
თავიდან ვთქვი რომ ოფშენალი იყო, მაგრამ მერე საუბარში მივხვდი ძალიან მნიშვნელოვანია ლოგიკა არ გეწეროს რეპოზიტორიში, შენთვის შეიძლება მოსახერხებელია, მაგრამ კოლაბორაციისთვის არის ცუდი.

2023-06-28 11:55 UTC, AleksandreGalogreBaramidze approved these changes

2023-07-04 07:21 UTC, merged