[CMOB-1795] Refactor: Design
bchmsl/QuizApp pull request #7
Opened 2023-06-27 13:04 UTC by bchmsl

https://spaceneobank.atlassian.net/browse/CMOB-1795

Added  progress bar for questions

2023-06-28 10:56 UTC, AleksandreGalogreBaramidze approved these changes

2023-06-28 20:33 UTC, Gio481 requested changes

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/domain/usecase/questions/QuizSaveUserPointsUseCase.kt
> +data class SaveUserPointsRequest(val subjectTitle: String, val points: Int)
ეს კლასი მოდელებში გაიტანე, აქ იუსქეისთან ერთად ფაილში არ გინდა

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/QuizNavigationView.kt
> +        binding.navTitleTextView
ზედმეტია ეს

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/fragment/QuizPointsFragment.kt
> +                logOutDialog.dismiss()
დისმისის დაწერა აქ არაა საჭირო დიალოგის კლასში გქონდეს

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/fragment/QuizPointsFragment.kt
> +                logOutDialog.dismiss()
ამის დაწერა არაა საჭირო დეფოლტად აკეთებდეს

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/vm/QuizPointsViewModel.kt
>      val userSubjects by QuizLiveDataDelegate<List<QuizUserSubjectUiModel>?>(null)
ნალის მნიშვნელობის დეფოლტად მიცემა არაა საჭირო

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/vm/QuizPointsViewModel.kt
> +            navigate(QuizFragmentDirections.START)
სტარტის მაგივრად ავტორიზაცია დაარქვი

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
>              nextButton.text = getString(S.next)
ნექსთ ბათონს ტექსტს აქაც ანიჭებ და 59 ხაზზეც და რატო

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +                progressView.setProgress(it.questionIndex + 1)
პლუს ერთის მაგივრად inc() გამოიყენე

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
>                  alertDialog.dismiss()
დისმისი არც აქ უნდა

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/vm/QuizQuestionViewModel.kt
>              >(emptyList())
დაწერე ისე რო ლაივდატებზე დეფოლტ მნიშვნელობების ჩაწოდება არ გჭირდებოდეს

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_points.xml
> +        android:paddingBottom="65dp"
ჰარდად გიწერია

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_points.xml
>          tools:visibility="gone" />
ისეც ხო წერია რო გამქრალია ვისიბილითი და ტულსი აღარ უნდა

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_points.xml
> +        tools:layout_editor_absoluteX="16dp"
აბსოლუტ იქსის ატრიბუტი არაა საჭირო

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_fragment_question.xml
>          tools:layout_editor_absoluteX="16dp"
აქაც აღარ უნდა აბსოლუტ იქსის ატრიბუტი

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_layout_dialog_prompt.xml
> +            app:layout_constraintTop_toBottomOf="@+id/promptTextView" />
36 ხაზზე არ უნდა @+id ასე ? :დ

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_view_navigation.xml
> +        app:layout_constraintHorizontal_bias="0.5"
ჰორიზონტალ ბიასი აღარ უნდა

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/layout/quiz_view_navigation.xml
> +        app:layout_constraintHorizontal_bias="0.5"
არც აქ გინდა ჰორიზონტალ ბიას

2023-06-28 20:33 UTC, Gio481 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_4_dp">4dp</dimen>
სპ და დპ არ აურიო ერთმანეთში და ზრდადობის მიხედვით დაალაგე

2023-07-04 07:31 UTC, Gio481 approved these changes

2023-07-04 07:31 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/common/util/QuizConstants.kt
> +    const val QUIZ_ENDPOINT = "8ade4e0b-bee1-4eae-a98b-47edeea68324"
ენდფოინთის კონსტანტა არაა საჭირო

2023-07-04 07:31 UTC, Gio481 commented on app/src/main/java/com/space/quizapp/common/extensions/utils/QuizUtilExtensions.kt
> +    backgroundTintList = ContextCompat.getColorStateList(
getColorState ექსთენშენი გაუშვი

2023-07-04 14:29 UTC, gioqemoklidze requested changes
შემდეგზე ამხელა ფაილჩეინჯებს ნუღარ გამოუშვებ , პს ვიუები და ადაპტერები მომწეონა როგორც გიწერია , კონფლიქტები გაასწორე

2023-07-04 14:29 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +            vm.navigate(QuizFragmentDirections.QUESTION, it.quizTitle)
same about navigations in this fragment

2023-07-04 14:29 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizAlertDialogView.kt
> +    }
remove empty init

2023-07-04 14:29 UTC, gioqemoklidze commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizPromptDialogView.kt
> +        }
same here

2023-07-05 08:46 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_start/fragment/QuizStartFragment.kt
> +
I want to format string with integers and how can I do it in viewmodel with only string resource?

2023-07-05 08:51 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +
I don't have UseCase for dialogs

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_start/fragment/QuizStartFragment.kt
> +    private fun setError(error: String) {
Done 🫡

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_start/fragment/QuizStartFragment.kt
> +                    vm.validateUser(it.toString().replace(" ", "").replace("\n", ""))
Done 🫡

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/fragment/QuizQuestionFragment.kt
> +
Done 🫡

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/vm/QuizQuestionViewModel.kt
> +    val isFinished by QuizLiveDataDelegate(false)
Done 🫡

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/vm/QuizQuestionViewModel.kt
> +                addPoints()
Done 🫡

2023-07-05 09:55 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_question/vm/QuizQuestionViewModel.kt
> +        executeAsync {
Done 🫡

2023-07-05 09:56 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/fragment/QuizPointsFragment.kt
> +        }
I will refactor all navigations in next commit 🫡

2023-07-05 09:56 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/QuizNavigationView.kt
>          binding.navTitleTextView.text = title
Done 🫡

2023-07-05 09:56 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizAlertDialogView.kt
> +        }
Done 🫡

2023-07-05 09:56 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizAlertDialogView.kt
> +    }
Done 🫡

2023-07-05 09:56 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/common/view/dialog/QuizPromptDialogView.kt
> +        }
Done 🫡

2023-07-05 12:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_points/fragment/QuizPointsFragment.kt
> +        }
Done 🫡

2023-07-05 12:31 UTC, bchmsl commented on app/src/main/java/com/space/quizapp/presentation/ui/ui_home/fragment/QuizHomeFragment.kt
> +            vm.navigate(QuizFragmentDirections.QUESTION, it.quizTitle)
Done 🫡

2023-07-05 12:32 UTC, bchmsl commented
@gioqemoklidze All requests are changed

2023-07-06 07:33 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/quiz_view_answer_option.xml
>              android:fontFamily="sans-serif"
sans-serif???

2023-07-06 07:37 UTC, bchmsl commented on app/src/main/res/layout/quiz_view_answer_option.xml
>              android:fontFamily="sans-serif"
Yes, I couldn't download Myriad, so I used sans-serif, which seem to work just as expected with Georgian alphabet

2023-07-06 11:34 UTC, DavitTsiskarashvili approved these changes

2023-07-06 13:26 UTC, gioqemoklidze approved these changes

2023-07-06 13:29 UTC, merged